#!/usr/bin/env sh

set -eu

cat <<EOF
class $name < Formula
  desc     "$desc"
  homepage "$page"
  version  "$vers"
  license  "(custom)"

  url "$repo",
    using: :git,
    branch: "$brch"

  uses_from_macos "zsh"

  def install
    system "make", "install", "prefix=#{prefix}"
  end

end
EOF
