#!/usr/bin/env sh

set -eu

homepage=$page
version=$vers

cat <<EOF
class $name < Formula
  desc     "$desc"
  homepage "$homepage"
  version  "$version"
  license  "(custom)"
  url "$repo",
    using: :git,
    branch: "$brch"

  uses_from_macos "zsh"

  def install
    system "make", "install", "prefix=#{prefix}"
  end

end
EOF
